enthought/traits-futures

- setup.py
> Add the long_description field in the setup.

- traits_futures/version.py
Version bump in preparation for 0.1.1 release.
> Bump version for 0.1.1 release

- setup.py
Adds author email, homepage url, keywords, and the Python 3.7 classifier.
> Add some missing setup keywords.

- ci/config.py
- docs/source/_static/README
- docs/source/conf.py
> Update documentation to use the Enthought Sphinx Theme

- traits_futures/tests/test_traits_executor.py
I commented on this and meant to fix this in #144.
> Fix nitpick identified but not fixed in an earlier PR

- traits_futures/traits_executor.py
This PR pulls out some tangential changes from #149, for ease of review of #149.
Apart from a couple of docstring changes, it represents only a behaviour-maintaining refactor of the logic to create the worker pool.
> Minor refactor of worker pool initialization code

- traits_futures/background_call.py
- traits_futures/background_progress.py
> Fix spelling mistakes

- traits_futures/api.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/i_future.py
- traits_futures/tests/common_future_tests.py
- traits_futures/tests/test_api.py
- traits_futures/traits_executor.py
[extracted from #163]
An an `IFuture` interface.
> Add IFuture interface

- traits_futures/qt/gui_test_assistant.py
This is an attempt to fix the test interactions observed in #175.
On my local machine, there's a clear difference: I can run the test suite 100 times in a row without failure on this branch, but the test suite tends to fail before the tenth run on master.
> Attempt to fix test interactions

- traits_futures/qt/gui_test_assistant.py
> Remove a spurious 'pass' statement

- ci/__main__.py
> Fix unblackened code introduced in PR #181

- traits_futures/version.py
The master branch is now aimed at the 0.3.0 release; bump the in-development version accordingly. (We'll branch from the previous commit to create the 0.2.0 release branch.)
> Bump version for continued development towards 0.3.0

- .github/workflows/check-style.yml
This PR adds a style check (via flake8) workflow, extracted and adapted from #237.
> Add GitHub Actions workflow for style checking

- .github/workflows/run-tests.yml
This PR extends the testing workflow to include testing on wxPython.
~Making this a draft PR because this will probably fail in one way or another.~
> Add testing for wxPython

- ci/config.py
Nitpicky change extracted from #173, to keep the branch for #173 clean.
This is inconsequential; review would be welcome, but I'll self-merge once CI completes.
> Fix an inaccurate comment

- docs/source/guide/examples/test_future.py
- docs/source/guide/testing.rst
- docs/source/index.rst
This PR adds some notes on how to test code that uses Traits Futures, along with an example.
> Add brief documentation on testing

- traits_futures/tests/traits_executor_tests.py
While developing for #334, we ran into hangs in the test suite involving `long_running_task`. This PR adds a timeout to the main `wait` call in `long_running_task` so that there's no possibility of it running indefinitely.
(Related: #310.)
> Make sure that long_running_task doesn't run forever

- docs/source/guide/advanced.rst
- docs/source/guide/cancel.rst
- docs/source/guide/contexts.rst
- docs/source/guide/overview.rst
- docs/source/guide/testing.rst
- docs/source/guide/toolkits.rst
- docs/source/index.rst
This PR makes each of the example scripts included in the documentation directly downloadable.
> Make all example scripts downloadable

- docs/source/conf.py
Style fix, courtesy of black. Will self-merge when CI completes.
> Fix black complaint

- traits_futures/tests/traits_executor_tests.py
Apply a style fix from black.
I'll self-merge this PR as soon as CI is complete.
> Style fix from black

- docs/source/changes.rst
- docs/source/guide/contexts.rst
> Mark multiprocessing support as provisional

- docs/source/conf.py
Fix to restore black-cleanliness.
> Style: keep black happy

- .github/workflows/publish-on-pypi.yml
This PR adds a workflow for uploading releases to PyPI.
Still to do (in this order):
Closes  #438
> Add workflow for uploading releases to PyPI

- docs/source/changes.rst
This is the first cut at a complete changelog for the 0.3.0 release.
> Changelog for 0.3.0

- traits_futures/version.py
Bump the version on the main branch for continued development towards the next feature release.
> Bump version for continued development

- traits_futures/version.py
Bump the version on the maintenance branch for any further development towards 0.3.1.
> Version bump for development towards 0.3.1

- docs/source/changes.rst
This PR updates the changelog to add a summary and a release date for 0.3.1.
> Update changelog in preparation for release of 0.3.1

- traits_futures/version.py
This PR bumps the version on the maint/0.3 branch for continued development towards 0.3.2.
> Bump version for continued development towards 0.3.2

- docs/source/changes.rst
This is a forward port of #469 to the main branch, merging the changelog changes in #469 with those on the main branch.
> Merge changelog updates

- .github/workflows/build-docs.yml
- scripts/update_docs.py
Still debugging the documentation auto-building
- The git username and email configuration needs to be global
- Use an explicit branch name to suppress output from `git init`
> More documentation auto-building

- ci/python_environment.py
- docs/source/guide/examples/headless.py
- docs/source/guide/examples/interruptible_task.py
- docs/source/guide/examples/non_interruptible_task.py
- docs/source/guide/examples/pi_iterations.py
- docs/source/guide/examples/prime_counting.py
This fixes CI failures due to black complaints. Note that black has finally reached a non-beta version, so future breakages like this should be rarer.
> Update style for most recent version of black
