- .travis.yml
Travis CI is rolling out Xenial everywhere, but our current method of starting the framebuffer doesn't work on Xenial. This PR fixes this to force use of Xenial and use the approved method for starting the framebuffer.
cf: enthought/envisage#159, enthought/traits#485
> Fix Travis CI configuration for Ubuntu Xenial

- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
Now that we're no longer supporting Python 3 there's no need to explicitly delete exception objects; Python will do that for us.
> Remove some redundant exception object deletions

- traits_futures/qt/message_router.py
Using `Iterable` from `collections` rather than `collections.abc` is deprecated. This PR fixes that.
> Fix DeprecationWarning for collections.Iterable

- docs/source/examples/quick_start.py
- examples/prime_counting.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
The `Unicode` trait type is deprecated since Traits 6.0.0, and `Str` is a drop-in replacement on Python 3 (even for Traits versions earlier than 6.0). This PR replaces all uses of the `Unicode` trait type with the `Str` trait type.
> Replace uses of the Unicode trait with Str

- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
Minor fix to a test helper function: make sure that we wait for all futures to complete before exiting the with block.
> Fix: clean up futures in test decorator

- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/tests/test_traits_executor.py
Nested test functions prevent the multiprocessing-equivalent of the thread executor, since they're unpickleable. This PR replaces them all with module-level functions.
> Replace nested test functions with module-level functions

- traits_futures/tests/test_traits_executor.py
- traits_futures/traits_executor.py
Closes #124 
This PR contains the minimal amount of changes to make the `max_workers` configurable, when the `TraitsExecutor` owns its own thread pool.
A couple things I'd like feedback on:
- An API problems I see, if `thread_pool` is provided, then `max_workers` does nothing.
- The other option discussed was to make this a trait on the `TraitsExecutor`. If we do this, do we respond to changes to `max_workers`? I could see something like the following work well:
```python
@on_trait_change('max_workers', post_init=True)
def replace_thread_pool(self, new):
if self._own_thread_pool:
self._thread_pool.shutdown()  # optionally, wait=False here
self._thread_pool = ThreadPoolExecutor(max_workers=new)
```
> Max workers is configurable

- ci/python_environment.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/null/event_loop.py
- traits_futures/null/gui_test_assistant.py
- traits_futures/null/message_router.py
- traits_futures/qt/gui_test_assistant.py
- traits_futures/qt/message_router.py
- traits_futures/tests/common_future_tests.py
- traits_futures/toolkit_support.py
Another post-Python2-migration cleanup: there's no longer any need to explicitly inherit from `object`.
> Don't explicitly inherit from object

- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
- traits_futures/tests/test_call_future.py
- traits_futures/tests/test_iteration_future.py
- traits_futures/tests/test_progress_future.py
This PR refactors the test structure for the various background calls to separate the tests themselves (which know nothing about threading or the parallelism mechanism that will be used) from the part that does need to know about the parallelism.
This is in preparation for adding multiprocessing support.
In more detail, `test_background_call.py` has been split into:
- `background_call_tests.py`, which defines a mixin class containing the actual tests, along with some helpers and assertion methods, but has no knowledge of parallelism (threading vs. multiprocessing vs. coroutines vs ...)
- `test_call_future.py`, a short test module containing tests for `CallFuture` (those tests don't depend on any parallelism, so we don't want to repeat them for multiprocessing)
- `test_background_call.py`, …
> Refactor tests to separate concurrency from parallelism

- traits_futures/tests/background_call_tests.py
This is a trivial nitpick-level PR to remove a use of the operator module.
> Remove an unnecessary use of the operator module

- CHANGES.rst
This was a leftover post-release action for the 0.1.1 release.
> Bring in changelog from release branch

- traits_futures/tests/test_api.py
Remove a check against names from future imports. This check is unnecessary now that we've removed Python 2 support.
> Remove future_imports check

- traits_futures/tests/test_traits_executor.py
One of the unit tests stopped the executor but failed to wait for that stop to complete. This PR fixes that.
> Fix a test that doesn't property stop the executor it creates

- CHANGES.rst
- docs/source/guide/intro.rst
- traits_futures/tests/test_traits_executor.py
- traits_futures/traits_executor.py
This PR:
- Renames the `thread_pool` argument to `TraitsExecutor` to `worker_pool`, to better fit with the anticipated case of supporting multiprocessing as well as multithreading. (It's also a better match with the `max_workers` name.)
- Makes the new `worker_pool` argument keyword-only.
- Keeps the `thread_pool` argument as as deprecated alias for `worker_pool`
- Makes the existing `max_workers` argument keyword-only. (Note that the `max_workers` feature has not yet been released, so this should not cause backwards compatibility issues.)
@jvkersch Unlike most of the recent PRs, this one actually changes functionality. Would you be willing to do a sanity check review?
> Rename TraitsExecutor thread_pool argument to worker_pool

- CHANGES.rst
- docs/source/guide/intro.rst
- traits_futures/background_progress.py
- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/traits_executor.py
Followup to #144: rename internal uses of 'thread_pool' to 'worker_pool'; no user-facing changes.
> Rename internal uses of 'thread_pool' to 'worker_pool'

- ci/__main__.py
Trivial quality of life PR: improve the `ci` help message.
Before:
```
mirzakhani:traits-futures mdickinson$ python -m ci
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
Development and continuous integration helpers for Traits Futures.
Options:
--help  Show this message and exit.
...
```
After:
```
mirzakhani:traits-futures mdickinson$ python -m ci
Usage: python -m ci [OPTIONS] COMMAND [ARGS]...
Development and continuous integration helpers for Traits Futures.
Options:
--help  Show this message and exit.
...
```
> Fix prog_name in ci helper

- ci/config.py
- ci/data/edm.yml
- examples/slow_squares.py
- tox.ini
- traits_futures/api.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/qt/init.py
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_api.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/traits_executor.py
Import orders are starting to be a cause of merge conflicts in refactoring; let's standardize them.
> CLN: Add import order checker

- traits_futures/qt/gui_test_assistant.py
This PR rewrites the `GuiTestAssistant.run_until` method to react to the trait change rather than polling the condition. As a result, the tests run significantly faster than before (under a second, versus over ten seconds on master, on my machine).
> React rather than polling in the Qt GuiTestAssistant

- docs/source/examples/quick_start.py
- docs/source/guide/intro.rst
- examples/pi_iterations.py
- examples/prime_counting.py
- examples/slow_squares.py
- traits_futures/api.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_api.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/traits_executor.py
[Pulled out of #163]
The `submit_*` convenience methods on the `TraitsExecutor` don't scale well: if we want to add a new background job type, we need to modify the `TraitsExecutor`. This particularly applies to 3rd party projects wanting to use their own background job type - those projects should be able to do so without feeling the need to modify the `traits_futures` source.
In effect, what we have is a violation of the OCP.
This PR deprecates the `submit_call`, `submit_iteration` and `submit_progress` methods of the `TraitsExecutor`, replacing them with convenience functions that are defined in the same place as the background jobs. It also updates all of the internal code and tests to use the new convenience functions (apart from three tests in `test_traits_executor.py` that have …
> Deprecate TraitsExecutor.submit_* methods; replace with functions

- traits_futures/traits_executor.py
Simple follow-up PR to #166: add note in the docstrings of the deprecated functions.
> Add missing deprecation notices to docstrings

- traits_futures/api.py
- traits_futures/i_parallel_context.py
- traits_futures/multithreading_context.py
- traits_futures/tests/test_api.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/traits_executor.py
This PR is a refactoring to pull out aspects of the TraitsExecutor that depend on the particular form of parallelism (e.g., threading versus multiprocessing) into a new `Context` object.
* Add new `IParallelContext` interface
* Add new `MultithreadingContext` implementing `IParallelContext`
* Add new `context` argument to the `TraitsExecutor`
* Use a `MultithreadingContext` by default if `context` is not provided.
This is part of the work towards supporting multiprocessing: we'll eventually define a `MultiprocessingContext` that can be used in place of `MultithreadingContext`.
> Separate parallelization from concurrency in TraitsExecutor

- README.rst
- docs/source/guide/intro.rst
- traits_futures/api.py
- traits_futures/future_states.py
- traits_futures/i_future.py
- traits_futures/tests/background_progress_tests.py
Also updates the `IFuture` docstrings and shuffles the order of the data and methods in `IFuture`.
> A few naming nitpicks and other minor changes extracted from #163

- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
- traits_futures/tests/test_traits_executor.py
This is another small step towards multiprocessing support: use the `MultithreadingContext` in tests, so that it's easy to switch it out for the future `MultiprocessingContext`.
> Use an appropriate context in tests

- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/traits_executor_tests.py
A minor reorganization of TraitsExecutor tests so that we can run those tests both for the multithreading and the multiprocessing contexts.
> Reorganize TraitsExecutor tests

- docs/source/api/traits_futures.api.rst
- docs/source/api/traits_futures.i_future.rst
- docs/source/api/traits_futures.i_parallel_context.rst
- docs/source/api/traits_futures.multithreading_context.rst
- docs/source/api/traits_futures.rst
- docs/source/conf.py
- traits_futures/api.py
- traits_futures/traits_executor.py
This PR:
- adds some missing API documentation modules
- removes duplicate index entries resulting from the autodoc of the api module
- adds intersphinx configuration
- fixes some broken references in docstrings
> API documentation fixes and updates

- docs/source/conf.py
- docs/source/index.rst
- traits_futures/null/gui_test_assistant.py
- traits_futures/qt/gui_test_assistant.py
This PR is a small collection of minor fixes:
- Add TraitsUI to intersphinx. We're not using it yet, but we'll likely need to shortly.
- Link directly to `concurrent.futures`
- Link properly to `HasTraits`
- Fix uses of `HasTraits` in docstrings so that Sphinx can resolve them properly.
> Minor documentation fixes

- CHANGES.rst
- README.rst
Tiny documentation fix: add missing copyright headers to `.rst` files. With this PR, all `.rst` files (including the autogenerated ones) have the copyright headers. (Verified manually using `find . -name \*.rst -exec head -3 {} \;`.)
> Add missing copyright headers to existing .rst files

- docs/source/guide/intro.rst
- docs/source/index.rst
The current docs have the heading "User Guide" nested under "User Documentation". This PR replaces the top-level heading with "User Guide", and the subheading with "Introduction". (This will work a bit better once #188 is merged.)
> Fix user guide documentation headings

- ci/__init__.py
- docs/source/conf.py
- traits_futures/null/__init__.py
- traits_futures/qt/__init__.py
- traits_futures/tests/__init__.py
This PR adds some more consistency fixes for copyright headers for *.py files
- Add missing copyright header for the documentation configuration file. While we're there, remove the unnecessary shebang and coding cookie lines.
- Remove copyright headers from files that would otherwise be completely empty.
> More copyright header consistency fixes

- CHANGES.rst
Add a changelog entry for the deprecation of the `TraitsExecutor.submit_*` methods.
This is really a dummy PR to test the new Appveyor CI configuration.
> Note deprecation of submit_call and friends in the changelog

- traits_futures/base_future.py
This is a drive-by nitpick-level fix, fixing inconsistent use of markup for future states in docstrings. No functional code was touched in the making of this PR.
> Fix inconsistent state markup in docstrings

- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/base_future.py
- traits_futures/tests/common_future_tests.py
- traits_futures/traits_executor.py
This is a minor refactor to make it easier for people to add their own background task types. (Related: #198.)
In the current code, a user who wants to create a new background task type writes a task specification class, and an instance `task` of that class must provide an attribute `future` that then gets called with `task.future(_cancel)`, to create  a future for the task.
The original issue in #200 was to rename the `_cancel` parameter so that it doesn't look like a private detail, but since the future method typically does nothing with that parameter except to pass it through to the `BaseFuture`, there's no real need for the task specification to know about it all. Instead, the `_cancel` callback can be provided to the future object _after_ creation.
Moreover, the current …
> Refactor to simplify provision of background task types

- .travis.yml
- appveyor.yml
This PR updates the EDM version in CI (travis/appveyor) from version 2.5.0 to 3.0.1
> Update edm version in CI

- ci/__main__.py
This PR adds a new `shell` click command - which when run activates the development environment for traits. The usual command line options are available to choose the runtime version/toolkit of the development environment. Underneath the hood, the click command just uses the `edm shell` command with the appropriate environment name, which is why the docstring for the click command is _almost_ the same as that of `edm shell`.
> Add a new shell click cmd

- docs/source/guide/advanced.rst
- traits_futures/base_future.py
- traits_futures/i_parallel_context.py
- traits_futures/multithreading_context.py
- traits_futures/tests/common_future_tests.py
- traits_futures/tests/test_base_future.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/wrappers.py
This PR:
- adds some new tests to improve test coverage
- removes some unused code, both from tests and from the main codebase
- makes the `BaseFuture.dispatch_message` method private (it's not useful to _users_ of Traits Futures, only to people extending Traits Futures), and removes an unnecessary redirection of message dispatch through a Trait in favour of calling `_dispatch_message` directly
- adds a couple of other small consistency cleanups
Closes #190.
> Clean up unused code, improve coverage

- traits_futures/base_future.py
- traits_futures/tests/common_future_tests.py
This PR improves the distinction between public code (essentially, the `BaseFuture` class) and the private details in the `base_future` module.  That's important because we're now encouraging people to subclass `BaseFuture` for their own background task types.
It does mean that we've now got another private import in the test suite. Possibly the relevant test should be moved to test_base_future.
> Make internal details of base_future private

- ci/__main__.py
- ci/python_environment.py
- examples/prime_counting.py
- examples/slow_squares.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_base_future.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/tests/test_message_router.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/traits_executor_tests.py
This PR brings the codebase back to black-compatible styling and applies a couple of other style fixes discovered while applying `black`.
- apply `black -l79 -tpy36 .`
- revert the changes to `docs/source/guide/examples/fizz_buzz_task.py`, to avoid extra blank lines in the built documentation
- fix two instances of `""""` to `"""`
- fix one docstring that starts on the same line as the opening `"""`. (That's not wrong, but it's inconsistent with all other docstrings in the package.)
> Apply black's styling to the codebase

- CHANGES.rst
This PR updates the changelog for the 0.2.0 release, and adds a tentative release date of September 24th (this Thursday).
I deliberately haven't included every PR in the detailed listing: some PRs were too minor to be included, or were refactoring PRs whose effects were reversed in a later refactoring. But all user-facing changes should be covered.
> Update changelog for the 0.2.0 release

- examples/pi_iterations.py
- examples/prime_counting.py
- examples/slow_squares.py
- traits_futures/traits_executor.py
Now that traits-futures does not support Python 2, we can get rid of the old way of calling `super`.
~Not sure if this needs to go into the release. I can update this PR again after #212 is merged.~
> Update super usage

- traits_futures/version.py
Now that 0.2.0 is released, the `maint/0.2.x` branch is aimed at the next bugfix release, 0.2.1. This PR bumps the version number accordingly.
> Bump version for development towards version 0.2.1

- traits_futures/null/message_router.py
The module docstring incorrectly referred to "Qt"; in fact, it's for the null toolkit.
> Fix message_router module docstring

- CHANGES.rst
The `state` trait of the various `Future` types changed from writable to read-only as part of the refactoring in #163. This broke at least one downstream application. While this change won't be reverted (the state trait should have been treated as read-only from the beginning), it's useful to note the change in the changelog.
This PR updates the changelog accordingly.
Closes #222
> Update changelog to mention read-only state

- docs/source/guide/advanced.rst
- traits_futures/base_future.py
- traits_futures/tests/test_base_future.py
- traits_futures/wrappers.py
We're planning to make the semi-private interface of `BaseFuture` public, for help with unit testing. (See #225.) So this is a good opportunity to review the method names and decide whether they're fit for public consumption - after we've make them public, it'll be harder to change them.
This PR makes one name change: `_dispatch_message` to `_task_sent`. This is primarily for consistency, making it clear where the external interactions come from in this semi-private interface. The other names will remain the same.
Notes:
- there's at least one project already using some of these methods, but it's not using `_dispatch_message`
- `_dispatch_message` _is_ documented, so could potentially have users, but I'm fairly sure that no-one is yet using it. It doesn't seem worth putting a deprecation …
> CHG: Rename BaseFuture._dispatch_message

- traits_futures/base_future.py
This PR represents some minor non-functionality-changing cleanups of the contents of the `base_future` module, motivated by the discussion in #224 
Closes #224 
Should be reviewable commit-by-commit, or in its entirety. Highlights:
- `_state` renamed to `_internal_state`, to avoid confusion between `state` and `_state`, and because the internal state is no longer simply a mirror for the user-facing state (unlike `_result` and `result`, or `_exception` and `exception`)
- replaced increasingly-complicated logic for computing the user-facing state from the internal state with a simple dictionary lookup
- simplified getters for the `done` and `cancellable` traits
- simplified and inlined `_InternalState`
- improved docstrings and comments
> CLN: Clean up of the base_future module

- traits_futures/null/init.py
- traits_futures/qt/init.py
Fix two occurrences of a trivial typo.
> Fix trivial typo in comment: reources -> resources.

- .travis.yml
- appveyor.yml
- ci/config.py
We're slowly moving towards making PySide2 the "standard" Qt backend, in preference to PyQt. And now that PySide2 is available under EDM, we can easily add it to the existing CI infrastructure.
This PR:
- updates the `ci` machinery to support PySide2 ("Qt for Python") in addition to PyQt4 and PyQt5
- adds Travis CI and Appveyor runs with the PySide2 toolkit
- makes PySide2 the default toolkit for users of `ci` (previously it was PyQt5)
> Support PySide2 Qt backend in Travis CI and Appveyor

- ci/__main__.py
Currently `python -m ci --help` works for getting help, but `python -m ci -h` does not. This breaks expectations of some users of command-line tools.
This PR makes `python -m ci -h` work for getting help.
(For @achabotl.)
> Support -h for getting help

- setup.py
This PR:
- removes `setuptools` from the `install_requires` list; it might have been needed once (for `pkg_resources), but it's not longer  a runtime dependency
- adds an `extras_require` section to make it easy to install Traits Futures with the support for a particular GUI toolkit; this will be useful when setting up the GitHub Actions continuous integration.
Note that we deliberately include a "null" toolkit list, even though it's empty, for the convenience of the upcoming GitHub Actions CI.
Fixes #238.
> Fix install_requires, add extras_require

- CHANGES.rst
- docs/source/index.rst
- setup.py
Officially drop Python 3.5 support. Traits, which we depend on, has dropped Python 3.5 support, and that's a good enough reason for Traits Futures to also drop it.
> Require Python 3.6 or later

- ci/__main__.py
- ci/python_environment.py
This PR fixes a potential issue with the current CI setup on Windows, namely that package modifiers like `"<4.1"` in `"wxPython<4.1"` get mangled by the `edm.bat` batch file used on Windows.
The solution is, on Windows, to replace any use of `edm.bat` with use of the corresponding system EDM executable. As a bonus, we also allow the path to the EDM executable to be specified in each of the `ci` commands.
This is the same issue that was solved for Traits in enthought/traits#512,  and it's currently blocking successful completion of CI runs in #246 in this repository.
> Use the EDM executable instead of the batch file on Windows

- examples/pi_iterations.py
The `pi_iterations` example was using numpy integers where it should have been using Python integers. That led to it giving incorrect results due to overflow.
Should fix #248. @rahulporuri: when you get a moment, could you please test on your machine?
> Make sure we use Python ints in pi_iterations example

- docs/source/conf.py
This PR adds two tweaks to the Sphinx configuration, in preparation for the documentation autobuilding machinery:
- Remove the "githubpages" extension, which was giving us a top-level .nojekyll file. Now that the documentation has moved down a level in the directory structure in the gh-pages branch, we don't need that file any more.
- Mock `wx` and `pyface.qt` imports, so that we don't need to have wxPython and PySide2 installed when building the documentation.
> Tweak Sphinx configuration: no .nojekyll, mock external imports

- traits_futures/tests/test_pinger.py
- traits_futures/wx/pinger.py
This PR simplifies the wx implementation of `Pingee` and `Pinger` slightly:
- Make the custom event a plain `wx.Event` instead of a `wx.CommandEvent`. From the documentation at https://wxpython.org/Phoenix/docs/html/events_overview.html, it looks as though we have no need for this event to be a `CommandEvent`: we don't need propagation, and if it does occur somehow then that could be potentially confusing.
- Make the event binder a module global - it apparently doesn't need to be per-object.
- Use `wx.lib.newevent` to create the new event type and corresponding binder (following [these](https://wxpython.org/Phoenix/docs/html/events_overview.html#custom-event-summary) docs)
- Add a test that instantiates multiple pingees, and verifies that pingers are only sending pings to the appropriate …
> Simplify the wx event code

- traits_futures/message_router.py
- traits_futures/null/pinger.py
- traits_futures/qt/pinger.py
- traits_futures/tests/test_pinger.py
- traits_futures/wx/pinger.py
This PR adds `connect` and `disconnect` methods to the `Pingee` (small-'i', implicit) interface. In particular, this gives the `wx` Pingee an opportunity to undo the binding that it made.
Closes #254.
> Add explicit Pingee connect and disconnect methods

- traits_futures/wx/pinger.py
PR #256 broke the documentation build:
```
(traits-futures) mdickinson@mirzakhani docs % python -m sphinx -b html -d doctrees -W source buildRunning Sphinx v3.3.1
making output directory... done
loading intersphinx inventory from https://docs.enthought.com/pyface/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.enthought.com/traits/objects.inv...
loading intersphinx inventory from https://docs.enthought.com/traitsui/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 35 source files that are out of date
updating environment: [new config] 35 added, 0 changed, 0 removed
reading sources... [100%] index …
```
> Fix documentation build

- .github/workflows/build-docs.yml
The automated documentation update appears to be working well, so it's time to move it from updating gh-pages-staging to gh-pages.
It's _possible_ that we'll run into branch protection issues with this change, but we won't find out about that until this PR is merged.
> Target gh-pages instead of gh-pages-staging for automated documentation builds

- .github/workflows/test-docs.yml
We'd like to detect potential automated documentation build failures _before_ they happen, rather than after.
This PR adds a per-PR test documentation build. The commands match the per-push-to-master documentation generation, except that this workflow is slightly stricter: it uses the "-W" option in the Sphinx build so that warnings get discovered sooner.
> Add a per-PR workflow to test the documentation build

- docs/source/api/templates/module.rst_t
- docs/source/api/templates/package.rst_t
This is a nitpicky documentation PR, intended to be used as a test of the documentation autobuilding. Do not merge before #257 is merged!
Currently, the autodoc templates used mean that the autogenerated module pages are missing a final newline: for example, see  the file at https://docs.enthought.com/traits-futures/dev/_sources/api/traits_futures.future_states.rst.txt . If you download and examine that file, you'll see a missing newline at the end. (Shock! Horror!)
This PR should fix that.
> Fix autodoc templates to avoid missing newline at EOF

- .travis.yml
This PR removes the (expensive) macOS builds on Travis CI, pending transition to GitHub Actions
> Turn off macOS builds on Travis CI

- .github/workflows/build-docs.yml
The default branch for this repository was recently changed from 'master' to 'main'. This PR updates the documentation build workflow accordingly. (This was the only part of the actual repository contents that needed to change.)
> Rename 'master' to 'main' in the documentation build workflow

- traits_futures/multiprocessing_router.py
- traits_futures/tests/test_multiprocessing_router.py
This PR is extracted from the long-running branch for #173.
This is the third PR in a planned series of four PRs aimed at adding multiprocessing support to Traits Futures
- The first PR, #231, introduced the `Pinger` and `Pingee` classes to better abstract over toolkits
- The second PR, #282, solidified the message routing machinery, added formal interfaces and refactored the existing multithreading routing machinery to match those interfaces.
- **This PR** adds a multiprocessing implementation of the new message routing interfaces.
- The last PR will add multiprocessing support at the level of the `TraitsExecutor`, adding a `MultiprocessingContext` to go alongside the existing `MultithreadingContext`.
For an overview of the mechanism, see the docstring of the `multiprocessing_router.py` …
> Add multiprocessing implementation of the message router interfaces

- traits_futures/multiprocessing_context.py
- traits_futures/multiprocessing_router.py
- traits_futures/tests/i_message_router_tests.py
- traits_futures/tests/test_multiprocessing_router.py
- traits_futures/tests/test_multithreading_router.py
[Code extracted from #173]
This is PR `<n>` in a series  of `<n+1>` PRs aimed at adding multiprocessing  support to Traits Futures. Previous PRs in the series are  #231, #282 and #283. There will be at least one more PR after this one, adding tests at the level of the Traits executor, and adding  `traits_futures.api`-level support.
This PR:
- Adds a new `MultiprocessingContext` class, parallel to the existing `MultithreadingContext` class, and implementing the existing `IParallelContext` interface.
- Adapts the existing message router tests to use a single context factory instead of using separate factories for the worker pool and message router
- Modifies the `MultiprocessingRouter` to require a manager to be passed in, instead  of having the router manage its own manager. This avoids …
> Add MultiprocessingContext, and adapt existing classes to use it.

- ci/__main__.py
- docs/source/guide/examples/interruptible_task.py
- docs/source/guide/examples/non_interruptible_task.py
- docs/source/guide/examples/test_future.py
- examples/pi_iterations.py
- examples/prime_counting.py
- examples/slow_squares.py
- tox.ini
- traits_futures/api.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/base_future.py
- traits_futures/i_message_router.py
- traits_futures/null/gui_test_assistant.py
- traits_futures/qt/gui_test_assistant.py
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/i_message_router_tests.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/traits_executor.py
- traits_futures/wx/gui_test_assistant.py
- traits_futures/wx/pinger.py
This PR fixes import orders and groups. The fixes should be enough to make the style check pass in #285.
Note: most of this PR came from simply applying `isort` to the codebase. The changes in the example scripts were made manually.
> Fix import grouping and ordering throughout the codebase

- .github/workflows/check-style.yml
- README.rst
- ci/__main__.py
- ci/config.py
- pyproject.toml
- setup.cfg
- tox.ini
This PR enhances the build machinery in various ways:
- use the `isort` package instead of using `flake8-import-order` to check import order
- rename the `python -m ci flake8` command to `python -m ci style`, since it now covers more than just flake8 checks
- add a new `python -m ci format` command that automatically sorts and groups imports
- fix missing help for `python -m ci shell`
- remove `FLAKE8_TARGETS`:  the information about which files to skip is moved to `setup.cfg`, where it belongs (that way it applies to all the various ways of invoking `flake8`, not just `python -m ci flake8`)
- move configuration to `setup.cfg`, since we can use this file both for `isort` and `flake8` configuration
- add configuration for the `black` utility, though we're not enforcing black style through …
> Replace flake8-import-order with isort

- .github/workflows/check-style.yml
- ci/__main__.py
- ci/config.py
- docs/source/guide/examples/.isort.cfg
- examples/.isort.cfg
[Followup to #285]
The Python files in the example directories have different import-order needs from the main codebase: in the examples, `traits_futures` is just another ETS package, so `traits_futures.api` imports should be placed into the same sections as `traits` and `traitsui` imports. In the main codebase, `traits_futures` is the local package, so its imports come after `traits` and friends.
This PR adds local `isort` configuration files for the two example directories, and extends the `ci format` and `ci style` commands to use those configurations.
> Extend 'ci format' and 'ci style' checks to example directories

- docs/source/conf.py
This PR fixes the appearance of the copyright statement at the bottom of each page of the rendered HTML documentation. The [Sphinx docs](https://www.sphinx-doc.org/en/master/usage/configuration.html) say that this should be "A copyright statement in the style '2008, Author Name'.", so we use that format.
Fixes #216
> Fix appearance of copyright in documentation

- examples/slow_squares.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
- traits_futures/tests/i_message_router_tests.py
This PR adds basic logging for message routers, and modifies one of the example scripts to make it easy to see the effect of that logging.
I'm deliberately not logging for every message sent / received; that would likely be too noisy. (For some applications, we could potentially have tens of such messages per second.)
Contributes to #24
> Adding logging for message routers

- .github/workflows/test-bleeding-edge.yml
This PR adds a workflow that runs the Traits Futures test suite once a week against the head of the Traits and Pyface default branches.
To do:
Closes #164.
> Add cron job that runs the test suite against the latest ETS source

- traits_futures/i_pingee.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
- traits_futures/null/pinger.py
- traits_futures/qt/pinger.py
- traits_futures/tests/test_pinger.py
- traits_futures/wx/pinger.py
This PR adds explicit `IPingee` and `IPinger` interfaces, mostly so that we can have meaningful type declarations in docstrings, and so that those docstrings don't confuse Sphinx.
Closes #281.
> Add IPingee and IPinger interfaces

- .github/workflows/test-bleeding-edge.yml
Our cron job currently tests on Python 3.6 and Python 3.9.  Internally we'll be running a lot of code on Python 3.8, so it makes sense to include that version, too, while keeping Python 3.9 so that we get alerted about possible issues with the bleeding edge version of Python. (At some point we'll likely replace the 3.9 run with a 3.10 run.)
> Add Python 3.8 testing for cron job

- docs/source/guide/intro.rst
- traits_futures/tests/traits_executor_tests.py
- traits_futures/traits_executor.py
We recently encountered hard-to-debug failures on a project; it eventually emerged that tasks were being submitted off the main thread, and with the current code, that's not supported. There are various potential issues, including that the internal state of the `TraitsExecutor` is not currently protected by locks, and that if Traits default methods (like the current `_message_router_default`) are invoked on a background thread, there are interesting failure modes (the message router is currently only designed to be instantiated on the main thread).
This PR raises an immediate exception on at attempt to submit a task from a background thread, so that we get an early clear failure rather than a late-discovered hard-to-debug intermittent failure.
EDIT: I've also tweaked the order of …
> Prevent task submission off the main thread

- traits_futures/asyncio/pinger.py
- traits_futures/i_pingee.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
- traits_futures/qt/pinger.py
- traits_futures/tests/test_pinger.py
- traits_futures/tests/test_toolkit_support.py
- traits_futures/wx/pinger.py
This PR is a minor refactor of the pingee / pinger infrastructure: it adds a `pinger` method to the `Pingee` class.
The advantage of this is that previously, instantiating a `Pinger` required both knowledge of the toolkit and of the associated `Pingee`. With this PR, knowledge of the toolkit is no longer required. This is a step towards the changes in #299 that aim to remove the toolkit magic from the majority of the codebase.
The PR also contains a minor inconsistency fix: in the `wx` implementation, the `Pinger` class came before the `Pingee` class, while in all other implementations the order was reversed. This PR fixes the order in the `wx` implementation to match that elsewhere.
[Extracted from #299]
> Add Pingee.pinger method

- traits_futures/asyncio/event_loop_helper.py
- traits_futures/i_event_loop_helper.py
- traits_futures/qt/event_loop_helper.py
- traits_futures/testing/gui_test_assistant.py
- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/tests/test_multiprocessing_router.py
- traits_futures/tests/test_multithreading_router.py
- traits_futures/tests/test_pinger.py
- traits_futures/tests/test_toolkit_support.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/test_traits_process_executor.py
- traits_futures/wx/event_loop_helper.py
Context: This is another incremental step towards the changes in #299. There are many more steps to go, including renaming. I'm avoiding renaming in this PR in an effort to keep the individual PRs reviewable.
This PR extracts a toolkit-specific `EventLoopHelper` class from the `GuiTestAssistant`, and makes the `GuiTestAssistant` non-toolkit specific.
There are various rationales:
- The `EventLoopHelper` can potentially be used outside a test context, or in more refined ways within tests.
- This allows the toolkit resolution in the `GuiTestAssistant` to be moved (in a future PR) to runtime rather than import time, which will eventually allow us to run tests for both the asyncio and Qt backends in a single test run.
> Extract toolkit-specific EventLoopHelper from the GuiTestAssistant

- traits_futures/multithreading_router.py
This PR fixes an inconsistency with `Pinger` instantiation. For the multiprocessing context and the tests, the `Pinger` is always instantiated on the worker thread. For the multithreading context, it's instantiated in the main thread and then used in the worker thread. There are toolkits where the thread affinity could potentially matter, so this PR changes the code to always instantiate the `Pinger` on the worker thread on which it'll be used.
> Always instantiate Pinger on the thread it'll be used on

- traits_futures/multiprocessing_context.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_context.py
- traits_futures/multithreading_router.py
- traits_futures/testing/gui_test_assistant.py
- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
- traits_futures/tests/test_multiprocessing_router.py
- traits_futures/tests/test_multithreading_router.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/test_traits_process_executor.py
- traits_futures/traits_executor.py
This PR refactors to remove most module-level uses of `ETSContext`, and to allow multiple `TraitsExecutor`s using different GUI toolkits to co-exist in the same process.
In detail:
- The `MultithreadingRouter` and `MultiprocessingRouter` classes now require an instance of `IGuiContext` to be supplied at creation time.
- The `MultithreadingContext` and `MultiprocessingContext` classes now take an optional `gui_context` argument; if that argument is not given, then they use the lazy `ETSContext`
- The GUI context in the `MultithreadingContext` is passed down to the `MultithreadingRouter` on creation; similarly for the multiprocessing variants
- The `GuiTestAssistant` creates an `ETSContext` instance in its `setUp`, and uses it for tests. A future PR will extend this so that different …
> Refactor: pull up ETSContext

- docs/source/guide/intro.rst
- traits_futures/api.py
- traits_futures/background_progress.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_api.py
This PR makes the `ProgressCancelled` exception used by the progress reporter and progress future public, and makes it available in `traits_futures.api`.
Fixes #316
> Make the ProgressCancelled exception public

- traits_futures/asyncio/event_loop_helper.py
- traits_futures/asyncio/tests/test_event_loop_helper.py
- traits_futures/i_event_loop_helper.py
- traits_futures/qt/event_loop_helper.py
- traits_futures/qt/tests/test_event_loop_helper.py
- traits_futures/tests/i_event_loop_helper_tests.py
- traits_futures/wx/event_loop_helper.py
- traits_futures/wx/tests/test_event_loop_helper.py
The goal of this PR is to add tests for each of the `EventLoopHelper` implementations, so that all relevant implementations of `EventLoopHelper` are tested by the test run. Before this PR, only the `EventLoopHelper` for the "current" toolkit was tested, via `test_gui_test_assistant`.
To test the event loop helper effectively, we also need general machinery to set a trait from within a running event loop. I've added a new method `IEventLoopHelper.setattr_soon` for that, following the same naming convention that `asyncio` uses (`call_soon`).
We also fix an omission in the `IEventLoopHelper` interface, namely that the abstract methods weren't decorated with `abc.abstractmethod`.
> Add tests for each of the IEventLoopHelper implementations

- traits_futures/testing/gui_test_assistant.py
- traits_futures/tests/test_gui_test_assistant.py
This PR changes the default context for the `GuiTestAssistant` to the one backed by `asyncio`; previously, it depended on `ETSContext`, whose behaviour in turn depended on the system context (particularly, the value of the `ETS_TOOLKIT` environment variable).
With this PR, the test run is no longer affected by the `ETS_TOOLKIT` environment variable. Instead, the Qt and Wx tests are run if and only if the corresponding toolkits are available. (And yes, in theory, this means that we could try to run both the Qt and Wx tests in the same test run. In practice, this went badly when I tried it: there was a hanging test, and I haven't yet figured out what went wrong.)
> Use the asyncio context by default for testing

- docs/source/guide/advanced.rst
- docs/source/guide/cancel.rst
- docs/source/guide/contexts.rst
- docs/source/guide/overview.rst
- docs/source/guide/testing.rst
- docs/source/index.rst
This PR skips the copyright headers in Python files included as documentation in the source.
For an example of how those headers currently appear, see the example in the "Quick Start" section of the main page of the documentation: https://docs.enthought.com/traits-futures/0.2/index.html#quick-start
> Doc: remove copyright headers from code literalincludes

- docs/source/guide/overview.rst
- docs/source/guide/testing.rst
The new overview section of the documentation introduced in #325 ended rather abruptly, mostly because I wanted to get a PR in. This PR fleshes out that last section slightly.
> Flesh out last section of the overview

- traits_futures/asyncio/event_loop_helper.py
Currently when testing with asyncio we attempt to create a fresh event loop for each test. This was a piece of defensive programming, aimed at avoiding accidental interactions between different unit tests via the shared state of the current event loop.
However, in doing this we're fighting the way that asyncio is designed (with the event loop being implicitly and lazily created on first use, and having no way to tell whether an event loop has already been created or not), and we end up debugging spurious resource warnings from unclosed event loops. It seems to be simpler to accept the more natural asyncio workflow of having a single main-thread event loop that's active from the time it's first accessed until the end of the process.
> Don't try to use a new event loop for every test

- traits_futures/asyncio/context.py
- traits_futures/asyncio/event_loop_helper.py
- traits_futures/asyncio/pingee.py
- traits_futures/asyncio/tests/test_event_loop_helper.py
- traits_futures/qt/tests/test_event_loop_helper.py
- traits_futures/tests/i_event_loop_helper_tests.py
- traits_futures/wx/tests/test_event_loop_helper.py
For asyncio, the event loop used by the Pingee and by the EventLoopHelper need to be the same event loop; the event loop really belongs to the context.
This PR:
- pushes the event loop up to the `AsyncioContext`, and passes it from there to the `Pingee` and `EventLoopHelper`; this way we're only using `asyncio.get_event_loop` in a single place.
- reworks the tests for the `EventLoopHelper` to use a factory for the GUI context rather than a factory for the event loop helper. This way the tests are creating the `EventLoopHelper` in the same way that the `EventLoopHelper` is created elsewhere.
> Move event loop to AsyncioContext

- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/test_traits_process_executor.py
This PR contains a simple drive-by fix to a couple of `tearDown` methods that aimed to shut down an executor in an unknown state: those methods attempted to call `stop` if the executor wasn't already stopped, but in the case that the executor is in `STOPPING` state that's an error. Instead, we need to call `stop` if the executor is running, and then wait for stop if the executor hasn't yet stopped.
> Don't call stop on a STOPPING executor

- .github/workflows/run-tests.yml
- .github/workflows/test-bleeding-edge.yml
One of the CI runs for #334 ran into a segfault. This PR enables faulthandler during test runs so that we get more information on the cause of the segfault next time this happens.
> Enable faulthandler when running tests

- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/test_traits_process_executor.py
Some executor tests weren't correctly passing in the GUI context from the testing framework. This PR fixes that.
> Fix executor tests that weren't correctly specifying the GUI context

- traits_futures/tests/traits_executor_tests.py
Follow-on to #338, change extracted from #334.
A test in the upcoming PR #334 encountered a race condition when using `long_running_task`. The test assumed that the task would already be executing by the time the associated with block was entered, but that's sensitive to timing.
This PR tightens the behaviour so that by the time the with block is entered it's safe to assume that the long-running task is already executing.
> Fix potential race condition in long_running_task

- traits_futures/asyncio/pingee.py
- traits_futures/i_pingee.py
- traits_futures/qt/pingee.py
- traits_futures/tests/i_pingee_tests.py
- traits_futures/wx/pingee.py
This PR fixes an issue in communication between a Pingee and an associated Pinger: if a Pinger continues to send pings after the "disconnect" method of the Pingee has been called, then the behaviour was ill-defined and differed from toolkit to toolkit.
With this PR,
- a Pinger can still be created after the Pingee.disconnect method has been called, and
- the Pinger can still send a ping after the Pingee.disconnect method has been called, but
- that ping will have no effect
To explain why the first bullet point above is important: the usual workflow is that:
- a `Pingee` object is created in the main thread
- that `Pingee` object is passed to background worker threads
- the `Pinger` object is created via the pingee's `pinger` method in the worker thread
It's possible (albeit unlikely in …
> Fix temporal coupling between Pingee and Pinger

- docs/source/guide/intro.rst
- traits_futures/api.py
- traits_futures/executor_states.py
- traits_futures/traits_executor.py
[Extracted from #334]
This PR extracts the refactoring and cleanup component of #334. The main aim is to remove the refactoring noise from #334 so that the functional changes in #334 are clearer and easier to review.
In detail:
- the executor states have been moved into their own top-level module, similar to the existing module for the future states
- machinery to support an internal state for the `TraitsExecutor` has been added. Right now the internal state exactly matches the actual state, but that will change with #334, which adds a new internal state that maps to the external `STOPPING` state.
- the order of wrapper creation in the `submit` method has been switched. This should have no visible effect, but is needed for #334 so that we can record the concurrent.futures `future` in the …
> Refactor executor states and shutdown

- traits_futures/tests/i_pingee_tests.py
This PR fixes a recently-introduced test that failed to call `join` on its background thread.
I'm hopeful that this will fix #340.
> Fix a test that created a thread but failed to join in

- traits_futures/traits_executor.py
Fix idiotic typo introduced in #346.
> Fix missing 'f' prefix on what was supposed to be an f-string.

- DEVELOP.rst
- MANIFEST.in
- README.rst
This PR removes the development instructions from the project README (which is what appears on the PyPI page) and moves them into a separate DEVELOP.rst document. I've also rewritten the README from scratch to give a more up-to-date description of what Traits Futures is.
Closes #215.
> Remove developer guide from README

- docs/source/changes.rst
This PR adds a section to the changelog, and adds a note about the backwards incompatible change introduced in #344.
Will self-merge when CI completes.
> Add section for backwards-incompatible changes to the changelog

- traits_futures/tests/background_call_tests.py
- traits_futures/traits_executor.py
- traits_futures/wrappers.py
Minor refactor, that doesn't touch published interfaces: instead of passing the `cancel_event` event to the `BackgroundTaskWrapper`, pass the `cancel_event.is_set` bound method. This matches [what's done](https://github.com/enthought/traits-futures/blob/7d3ae40569f9313a819da726bbb823a1840e46b6/traits_futures/traits_executor.py#L301) with the `FutureWrapper` (passing `cancel_event.set` rather than `cancel_event`), and also matches the `BackgroundTaskWrapper` [docstring](https://github.com/enthought/traits-futures/blob/7d3ae40569f9313a819da726bbb823a1840e46b6/traits_futures/wrappers.py#L102-L104), which was previously incorrect.
> Refactor: fix wrapper asymmetry (and inaccurate docstring)

- traits_futures/base_future.py
- traits_futures/wrappers.py
Minor refactoring of the wrapper machinery:
- fix unnecessary nesting in the message structure - messages that were previously of the form `(CONTROL, (RETURNED, value))` now have the form `(RETURNED, value)` and similarly for `RAISED` and `STARTED`. Messages that were previously of the form `(CUSTOM, message)` now have the form `(SENT, message)`. This allows all of these messages to be treated uniformly in the `FutureWrapper`.
- ~the `BaseFuture` methods that receive messages from the wrapper now return a boolean that's `True` if this is expected to be the last message received~
- don't listen to the `Future`'s "done" trait; instead, use the message type to determine when to tell the executor to clean up. This means that all the effects of the future state change will happen strictly …
> Simplify messages, ensure cleanup ordering

- docs/source/changes.rst
- docs/source/guide/advanced.rst
- docs/source/guide/examples/fizz_buzz_task.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/i_task_specification.py
- traits_futures/wrappers.py
This PR represents a backwards-incompatible change to the `ITaskSpecification` interface: the `send` callable that's passed to the background task now expects a single argument rather than a pair of arguments of the form `message_type, message_arg`.
The reason for the change is both to simplify the existing code and to remove an unnecessary constraint on custom future types. The general executor machinery should not know or care about the form of the messages passed from a user-defined background task to the corresponding user-defined future, but currently it _does_ need that knowledge, because the `send` callable that it passes to the background task needs to have the correct signature. I consider this a design mistake in the current code, and one that it's better to fix sooner rather …
> ITaskSpecification change: 'send' expects a single argument

- .github/workflows/build-docs.yml
- .github/workflows/check-style.yml
- .github/workflows/run-tests.yml
- .github/workflows/test-bleeding-edge.yml
- .github/workflows/test-docs.yml
A recent CI run appeared to hang during the test run, but didn't output any useful information. That _may_ have  been due to Python output being buffered, or it may have been something else. This PR sets [PYTHONUNBUFFERED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED) for all workflows, in the hope that we get more useful output next time this happens. (This is something we've had to do previously on Travis CI and Appveyor.)
(Test run: https://github.com/enthought/traits-futures/runs/2990762656?check_suite_focus=true)
> Set PYTHONUNBUFFERED in all workflows

- docs/source/guide/examples/fizz_buzz_ui.py
- docs/source/guide/examples/interruptible_task.py
- docs/source/guide/examples/non_interruptible_task.py
- docs/source/guide/examples/pi_iterations.py
- docs/source/guide/examples/prime_counting.py
- docs/source/guide/examples/quick_start.py
- traits_futures/tests/traits_executor_tests.py
This PR replaced `depends_on` with `observe` for `Property` traits using automated search-and-replace. After the search-and-replace, one of the change needed to be corrected from `x:done` to `x:items:done` because `x` was a container trait. All of the changes in example files have been checked.
This PR is one step towards #356.
> Replace "depends_on" with "observe" for "Property" traits

- docs/source/guide/examples/pi_iterations.py
- docs/source/guide/examples/prime_counting.py
- docs/source/guide/examples/quick_start.py
- docs/source/guide/intro.rst
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/common_future_tests.py
- traits_futures/tests/i_event_loop_helper_tests.py
- traits_futures/tests/i_message_router_tests.py
- traits_futures/tests/traits_executor_tests.py
- traits_futures/traits_executor.py
- traits_futures/wrappers.py
This PR replaces the `on_trait_change` decorator with the `observe` decorator. The changes have been made in the documentation, the testsuite and the package itself.
Note that the new decorator requires a change to the signature of the decorated method - which now needs to accept a single `event` argument instead of the earlier signature.
This PR is one more step towards #356
> Replace "on_trait_change" decorator with "observe" decorator

- traits_futures/base_future.py
- traits_futures/traits_executor.py
This PR replaces static trait change handlers (`_trait_name_changed` named methods ) with methods decorated with `observe`.
This is one more step towards #356 .
> Replace static trait change handlers with "observe" decorated methods

- docs/source/changes.rst
- setup.py
- traits_futures/asyncio/event_loop_helper.py
- traits_futures/qt/event_loop_helper.py
- traits_futures/tests/common_future_tests.py
- traits_futures/tests/traits_executor_tests.py
- traits_futures/wx/event_loop_helper.py
This PR replaces the dynamic use of `on_trait_change` e.g. `object.on_trait_change(...)` with `observe` i.e. `object.observe(...)`.
Along with #370 , #371 , #372, this PR fixes #356 .
Note that these changes make Traits Futures depend on Traits >= 6.2.0, which is explicitly listed in the setup script. A small note has been added to the changelog as well.
> Replace dynamic use of "on_trait_change" handlers with "observe"

- docs/source/guide/examples/headless.py
- pyproject.toml
Update the black list of excluded files to exclude just the one troublesome file, and to explain why it's being excluded.
Also fix some non-black code that slipped by as the result of the more general exclusion.
Upstream issue: https://github.com/sphinx-doc/sphinx/issues/9407
> Only exclude one troublesome example, not all of them

- traits_futures/testing/gui_test_assistant.py
- traits_futures/tests/i_pingee_tests.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/tests/traits_executor_tests.py
This PR adds a new GuiTestAssistant.exercise_event_loop function and
refactors two existing test cases to make use of it.
exercise_event_loop simply runs the GUI event loop, in the hope of
flushing out any pending GUI events. It's useful for tests of the
form "nothing bad happens when the event loop is run". It's not
useful for tests that require pending events to be processed
by the event loop; that's a much harder problem to solve in general.
> Add GuiTestAssistant.exercise_event_loop

- docs/source/guide/intro.rst
- traits_futures/tests/traits_executor_tests.py
- traits_futures/traits_executor.py
- traits_futures/wrappers.py
This PR updates the executor shutdown so that it routes messages as usual during the blocking shutdown. It also removes some now-unused machinery introduced in #334 and #344: there's no longer any need to wait for the concurrent.futures futures, so we don't need to keep them around in the wrapper class.
At behaviour level: a future that's cancelled due to shutdown _will_ now reach the `CANCELLED` state as usual.
At implementation level: we make use of the new `IMessageRouter.route_until` method introduced in #378.
This PR exposes some opportunities for refactoring (beyond simple removal of unused pieces), but those can be pursued in a separate PR that doesn't change behaviour.
> Route messages during executor shutdown

- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
This is a small refactor in `submit_progress` to move the detection of an invalid `progress` keyword earlier. This enables the removal of a [try/except in `TraitsExecutor.submit`](https://github.com/enthought/traits-futures/blob/077e8b9b6d871c2273fb9781063991fa86bcd688/traits_futures/traits_executor.py#L306-L312). I haven't included that removal in this PR, because it will conflict with other currently open PRs.
While we're here, we also remove unnecessary dict `copy` operations from all three background task types, and simplify the code that calls the background task.
> Refactor to move 'progress' argument check in submit_progress

- traits_futures/asyncio/pingee.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
- traits_futures/tests/i_pingee_tests.py
- traits_futures/wx/pingee.py
For safety, Qt requires that objects that are owned by the main thread should be collected on the main thread. Quoting from https://doc.qt.io/qt-5/threads-qobject.html#per-thread-event-loop:
> Calling delete on a QObject from a thread other than the one that owns the object [...] is unsafe
We've seen segfaults previously that likely arise from violating this constraint (xref: #340), so it doesn't seem like a purely theoretical concern.
But when combined with Python's refcount and cycle-based garbage collection model, this is problematic for the Qt `Pingee` class in Traits Futures. Each `Pingee` object is owned by the main thread, but we have both main-thread and worker-thread references to a `Pingee` object. In order to ensure that the `Pingee` is collected on the main thread, we need to …
> Ensure that Pingees are always collected on the main thread

- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_gui_test_assistant.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/test_traits_process_executor.py
This PR updates tests in the test suite to use the executor's `shutdown` method in preference to the `stop` method, where that makes sense. The tests for `stop` itself still use the `stop` method, of course.
> Update tests to use shutdown

- docs/source/guide/contexts.rst
- docs/source/guide/examples/background_processes.py
- docs/source/guide/examples/fizz_buzz_ui.py
- docs/source/guide/examples/interruptible_task.py
- docs/source/guide/examples/non_interruptible_task.py
- docs/source/guide/examples/pi_iterations.py
- docs/source/guide/examples/prime_counting.py
- docs/source/guide/examples/quick_start.py
- docs/source/guide/examples/slow_squares.py
- docs/source/guide/examples/test_future.py
- docs/source/guide/testing.rst
This PR updates the examples to better show best practices with respect to executor creation and shutdown:
- Always use 'shutdown' to shut the executor down.
- Remove examples of the `Instance(TraitsExecutor, ())` antipattern, with its implicit executor creation
There's also some drive-by cleanup:
- Be consistent about the executor attribute: before we had a mixture of `self.executor` and `self.traits_executor`; now we have only `self.traits_executor`
- Now that we're doing executor shutdown externally to the running UI, we no longer need to use `Handler` from TraitsUI, and we no longer need to implement the `closing` method in our UIs
Finally, we also update the advice in `testing.rst` about executor cleanup: it now mentions `shutdown` as the preferred way to shut down an executor. …
> Update examples to use 'shutdown'

- traits_futures/asyncio/tests/test_pingee.py
- traits_futures/qt/tests/test_pingee.py
- traits_futures/testing/test_assistant.py
- traits_futures/tests/i_event_loop_helper_tests.py
- traits_futures/tests/i_message_router_tests.py
- traits_futures/tests/i_pingee_tests.py
- traits_futures/tests/test_background_call.py
- traits_futures/tests/test_background_iteration.py
- traits_futures/tests/test_background_progress.py
- traits_futures/tests/test_multiprocessing_router.py
- traits_futures/tests/test_multithreading_router.py
- traits_futures/tests/test_test_assistant.py
- traits_futures/tests/test_traits_executor.py
- traits_futures/tests/test_traits_process_executor.py
- traits_futures/wx/tests/test_pingee.py
Step towards #304: this PR renames the Traits Futures `GuiTestAssistant`, to avoid confusion with the existing Pyface `GuiTestAssistant`.
The only problem is figuring out what to name it *to*. My first thought was `TraitsFuturesTestAssistant`, but that's getting a bit long. Instead we simply use `TestAssistant` (thanks @itziakos for the suggestion); users can make use of the context to disambiguate if necessary.
> Rename GuiTestAssistant to TestAssistant

- traits_futures/base_future.py
- traits_futures/tests/common_future_tests.py
Closes #358. The fix was trivial. Writing tests for it wasn't quite so easy.
> Make sure that the cancellation callback is always cleared

- traits_futures/base_future.py
- traits_futures/tests/common_future_tests.py
- traits_futures/wrappers.py
This is a slight cleanup of the `BaseFuture` and wrapper logic.
Previously, when execution of the background task's callable was abandoned due to cancellation, we acted as though it had run anyway, sending a STARTED message followed by a RETURNED message (with an argument of None) to the future. That was slightly smelly (inventing a return result when none existed), and involved sending and processing two messages when one would have been sufficient.
This PR introduces a new ABANDONED message for this. It also:
- expands the `CANCELLED` future state into three different internal states, depending on whether the task's callable completed, failed, or was never executed (abandoned)
- keeps the result and/or the exception information from the background task even when cancellation occurred. …
> Refactor to add ABANDONED message

- traits_futures/tests/common_future_tests.py
There are now comments at the top of the test module that describe the messages and valid message sequences; we can remove this one.
> Remove comment that was both redundant and out of date

- traits_futures/i_future.py
The `IFuture` interface declares a `message` trait that was a leftover from refactoring: it's not implemented by any of the concrete implementations, and is not used. This PR removes it.
> Remove bogus "message" trait from IFuture

- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/tests/background_iteration_tests.py
This PR renames some internal classes that aren't exposed in `traits_futures.api`:
`BackgroundCallTask` -> `CallTask`
`BackgroundIterationTask` -> `IterationTask`
`BackgroundProgressTask` -> `ProgressTask`
The original names are unwieldy, and the `Background` portion of the names is both inaccurate (objects of these classes could equally well be run in any thread) and doesn't add anything useful.
> Rename task classes

- traits_futures/exception_handling.py
- traits_futures/tests/test_exception_handling.py
The `marshal_exception` function used `formatted_traceback = str(traceback.format_exc())` to format the traceback, which implicitly picked up the exception details from `sys.exc_info()`. This meant that it only worked correctly from within an "except" block (which is the only way that we're currently using it). This indirection may have been necessary in Python 2, but for Python 3 we can access the traceback directly from the exception object.
This PR fixes `marshal_exception` to use the actual exception traceback.
While we're here, we also improve the `marshal_exception` docstring and tidy up the implementation.
> Fix marshal_exception not to use global state

- traits_futures/exception_handling.py
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_exception_handling.py
[PR made against the branch for #390, for ease of review]
This PR changes the representation of the exception class used when reporting exceptions. Previously we just used the `str` of the exception class, giving strings like `"<class 'RuntimeError'>"`. With this PR we give a more direct string, including the module name where appropriate, for example `"RuntimeError"` or `"struct.error"`
Fixes #379.
See also #318.
> Change string representation of marshalled exception type

- traits_futures/tests/traits_executor_tests.py
- traits_futures/traits_executor.py
Fix an f-string that wasn't.
To do: could use a regression test.
> Fix bad string interpolation in shutdown log message

- traits_futures/i_message_router.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
Fix three misplaced documentation descriptions, which confuse the napoleon Sphinx extension.
> Doc: fix descriptions coming after Parameters

- traits_futures/asyncio/event_loop_helper.py
- traits_futures/asyncio/pingee.py
- traits_futures/multiprocessing_router.py
Fix incorrect references to `AbstractEventLoop` and `multiprocessing.Manager` that Sphinx was unable to resolve.
Will self-merge when the CI completes.
> Doc: fix bad standard library references

- docs/source/guide/examples/fizz_buzz_task.py
- traits_futures/asyncio/event_loop.py
- traits_futures/asyncio/event_loop_helper.py
- traits_futures/asyncio/pingee.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/base_future.py
- traits_futures/ets_event_loop.py
- traits_futures/i_event_loop.py
- traits_futures/i_event_loop_helper.py
- traits_futures/i_message_router.py
- traits_futures/i_pingee.py
- traits_futures/i_task_specification.py
- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
- traits_futures/qt/event_loop.py
- traits_futures/qt/event_loop_helper.py
- traits_futures/qt/pingee.py
- traits_futures/testing/test_assistant.py
- traits_futures/tests/i_pingee_tests.py
- traits_futures/traits_executor.py
- traits_futures/wrappers.py
- traits_futures/wx/event_loop.py
- traits_futures/wx/event_loop_helper.py
- traits_futures/wx/pingee.py
Fix Sphinx warnings resulting from Napoleon trying to interpret "callable" as a type. In almost all cases, the "callable" description is redundant and we simply remove it.
> Fix 'callable' type descriptions

- traits_futures/i_parallel_context.py
- traits_futures/multiprocessing_context.py
- traits_futures/multithreading_context.py
Replaces "event-like" with just "object", and makes the descriptions match between the interface and its implementations.
We _could_ introduce an actual interface, but it doesn't seem worth it.
> Remove 'event-like' as a type

- traits_futures/multiprocessing_router.py
Remove unresolvable references in the docstring for the `multiprocessing_router` module.
> Docs: remove unresolvable references

- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
This PR updates the docstrings of `submit_call`, `submit_iteration` and `submit_progress` to note that the `executor` and `callable` arguments to those functions should be treated as being positional-only (and may actually become positional-only when we can drop support for Python 3.6 and 3.7).
Closes #369.
> Document 'positional-only' arguments

- docs/source/guide/advanced.rst
- docs/source/guide/examples/fizz_buzz_task.py
- traits_futures/api.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/base_future.py
- traits_futures/i_future.py
- traits_futures/tests/test_api.py
- traits_futures/traits_executor.py
- traits_futures/wrappers.py
This PR refactors the `TraitsExecutor`, wrapper, and `BaseFuture` machinery to better decouple the `TraitsExecutor` from the tasks it's executing. 
Previously, the `TraitsExecutor`, via the `BackgroundTaskWrapper`, sent messages of types `STARTED`, `RAISED`, `RETURNED`, `ABANDONED` and `SENT` to the future, and relied on the machinery in the `BaseFuture` to interpret those messages. The knowledge of the message types was partly encoded in the wrapper and partly in the `BaseFuture`.
But the `TraitsExecutor` needs much less than this: it shouldn't care about the details of these messages and their formats. All it cares about is that it can:
- send arbitrary messages received from a background task to its corresponding future
- know when a future has completed
- know when a future is …
> Decouple TraitsExecutor from future implementation

- .github/workflows/weekly-scheduled-tests.yml
This PR sets up the slack notifications for cron jobs on this repository. I manually triggered the cron job on this repository to ensure that the slack notification does get fired as expected. Ref https://github.com/enthought/traits-futures/actions/runs/1027349871.
One more step towards https://github.com/enthought/ets/issues/65.
> Setup slack notifications for cron jobs

- .readthedocs.yaml
- setup.py
This PR adds a basic configuration file for Read the Docs. These changes are based on https://github.com/enthought/traits/pull/1478. Along with the configuration file, I added a new `docs` `extras_require` to make it easy to install the additional requirements needed to build docs.
Ref https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install to understand the configuration file better.
~Note : Unlike the traits PR, I am unable to figure out where (URL) the docs built on this branch URL exist. I'm only seeing failed builds on https://readthedocs.org/projects/traits-futures/builds/ and they're all built from the `main` branch instead of this branch e.g. https://readthedocs.org/projects/traits-futures/builds/14237319/. I feel like there might be an issue with settings on …
> Add RtD config file

- .github/workflows/check-style.yml
A number of style-related problems have snuck into the main branch recently; I habitually run `black` while developing, so these show up as extraneous changes in PRs.
So with this PR I'm finally biting the bullet and adding a `black` check to the style checks, so that the `main` branch stays black-clean.
N.B. If the new style check works, this PR should fail. It'll pass once #415 is merged into this branch (via main).
> Add black check to the style checks

- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
This PR simultaneously improves a failure mode *and* makes failure more likely. :-)
In more detail:
When a message is sent from a background task to the corresponding future, the following sequence of events occurs:
1. The background task puts the message on the message queue (a regular `queue.Queue` instance)
2. The background task sends a "ping" to the message router to let it know that there's a message to be processed
3. When the message router receives the "ping", it gets the message from the message queue and dispatches it.
Currently, in the main branch, for step 3 we use a blocking `message_queue.get()` operation to get the message. In effect we're assuming that if a message has been put on the queue, `message_queue.get()` will not block for long while the message is retrieved. If …
> Remove the blocking wait during message routing

- docs/source/conf.py
- docs/source/guide/advanced.rst
- docs/source/guide/examples/fizz_buzz_task.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/base_future.py
- traits_futures/i_task_specification.py
- traits_futures/tests/common_future_tests.py
- traits_futures/tests/test_base_future.py
- traits_futures/traits_executor.py
This PR builds on #396 to further decouple the `TraitsExecutor` from the details of the `IFuture` objects.
The motivating change is to remove the need for the executor to call `future._executor_initialized(cancel.set)`: https://github.com/enthought/traits-futures/blob/e5510abb36a44eb3790640130b982ce6a802a4d4/traits_futures/traits_executor.py#L313
Instead we pass the cancellation callback to the `future` method, which in turn sets the corresponding trait directly. In addition, in this PR:
- The `BaseFuture._executor_intialized` method has been entirely removed
- The `_INITIALIZED` and `_NOT_INITIALIZED` states have been folded back into a the single `WAITING` state
- The `_cancel` trait in `BaseFuture` is now a required trait. (Note that this is a detail of the `BaseFuture` implementation, …
> More TraitsExecutor / IFuture decoupling

- traits_futures/base_future.py
We recently accidentally re-introduced some Sphinx warnings (see below). This PR fixes them.
```
/Users/mdickinson/Enthought/Projects/traits-futures/traits_futures/background_call.py:docstring of traits_futures.background_call.CallTask.run:6: WARNING: py:class reference target not found: callable
/Users/mdickinson/Enthought/Projects/traits-futures/traits_futures/background_call.py:docstring of traits_futures.background_call.CallTask.run:10: WARNING: py:class reference target not found: callable
/Users/mdickinson/Enthought/Projects/traits-futures/traits_futures/background_iteration.py:docstring of traits_futures.background_iteration.IterationTask.run:6: WARNING: py:class reference target not found: callable
/Users/mdickinson/Enthought/Projects/traits-futures/traits_futures/background_iterat …
```
> Fix Sphinx warnings about 'callable'

- docs/source/guide/intro.rst
This PR cleans up the links in `intro.rst`, mostly adding missing links to various attributes and traits. The substance of the documentation hasn't changed.
> Doc: clean up introduction references

- docs/source/guide/examples/prime_counting.py
[Extracted from #420]
This method should have been removed as part of #385, but wasn't. The `closing` trait exists on the TraitsUI `Handler` class, but since #385 we're no longer subclassing `Handler` and we have no need to cancel on exit - the shutdown machinery takes care of that for us.
> Remove an unused method

- traits_futures/base_future.py
`BaseTask.run` was missing its first `self` argument. This didn't actually affect any code, since the base class method is never called (it's only there as a placeholder to be overridden by subclasses), and all the subclasses have the correct signature.
> Fix missing 'self' in method definition

- traits_futures/i_future.py
The `IFuture`'s 'state' trait is declared as `FutureState`, but actually implemented as `Property(FutureState)`. This PR updates the interface to match reality.
> Fix 'state' trait type in IFuture

- docs/source/guide/advanced.rst
- traits_futures/base_future.py
- traits_futures/i_future.py
This PR addresses part of #354. (No, really!)
The "Creating your own background task type" portion of the docs discusses the `_task_sent` method, which is private and undocumented, and so we got Sphinx warnings as a result.
This PR extracts the part of that method that _needs_ to be public into a new public `BaseFuture.dispatch` method, and updates the docs accordingly.
One benefit is that the ``dispatch`` method is now the only part of `BaseFuture` that assumes that messages have the form `(message_type, message_arg)`, so it's the only part of `BaseFuture` that needs to be overridden if that assumption isn't convenient.
With this, we're down to 4 Sphinx warnings, all of which are about the `GuiTestAssistant`.
> Extract public 'dispatch' method from task_sent

- docs/source/guide/intro.rst
This PR fixes some incorrect Sphinx roles: attributes that were being referred to as methods.
> Doc: Fix some bad Sphinx roles

- docs/source/guide/testing.rst
Closes #354 (and then merging #429 should reinforce this by ensuring that the CI detects Sphinx warnings in future).
In theory, now that https://github.com/enthought/pyface/pull/933 is merged, we should be able to restore these links once a new version of Pyface has been released. However, the remaining tasks in the 0.3.0 milestone may eliminate the need to refer to the `GuiTestAssistant` altogether.
> Fix last of the Sphinx warnings

- ci/__main__.py
- docs/source/conf.py
Penultimate step towards solving #354: turn on nitpicky mode.
I'm expecting the CI to fail for this PR. It should pass after we've fixed the last of the broken references (in a separate PR: #430).
> Turn on nitpicky mode for documentation builds

- traits_futures/multiprocessing_router.py
- traits_futures/multithreading_router.py
- traits_futures/tests/i_message_router_tests.py
This PR modifies the behaviour of `route_until` so that it always processes messages that are already on the queue, regardless of the timeout given. Previously, given a small timeout, it would fail even when there were messages already present to be processed.
Key technical point for understanding the implementation: for a `queue.Queue`, the `get` operation always returns a result if there's one queued. (Relevant source: https://github.com/python/cpython/blob/919ad537510fdc2c750109e0bc4eceea234324b2/Lib/queue.py#L176)
Fixes #417
> Fix behaviour of route_until with timeout and queued messages

- docs/source/changes.rst
- docs/source/guide/advanced.rst
- docs/source/guide/examples/fizz_buzz_task.py
- traits_futures/background_call.py
- traits_futures/background_iteration.py
- traits_futures/background_progress.py
- traits_futures/i_task_specification.py
- traits_futures/traits_executor.py
- traits_futures/wrappers.py
A minor quality-of-life tweak: the `ITaskSpecification` interface requires implementers to supply two methods: `future` and `background_task`. The `background_task` name has long felt unwieldy. This PR renames it to simply `task`.
> Rename ITaskSpecification.background_task to ITaskSpecification.task

- docs/source/changes.rst
- docs/source/guide/examples/background_processes.py
- docs/source/guide/examples/prime_counting.py
- docs/source/guide/examples/slow_squares.py
- docs/source/guide/intro.rst
- traits_futures/base_future.py
- traits_futures/i_future.py
- traits_futures/tests/background_call_tests.py
- traits_futures/tests/background_iteration_tests.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/traits_executor.py
This PR changes the `IFuture.cancel` method to silently do nothing instead of raising `RuntimeError` when a future isn't cancellable. I believe that this better reflects the most common use-case.
See #398 for the original proposal and discussion.
Closes #418.
> Change cancel method to never raise

- docs/source/guide/advanced.rst
- docs/source/guide/examples/interruptible_task.py
- docs/source/guide/examples/non_interruptible_task.py
- docs/source/guide/intro.rst
- traits_futures/api.py
- traits_futures/base_future.py
- traits_futures/i_future.py
[Should only be considered for merging once #420 is merged - the code here assumes that `cancellable` is no longer needed by the executor]
`IFuture` is currently being used for two separate purposes: documenting the methods available to a user of the futures implementation, and documenting the methods that the executor expects to interact with.
For the first purpose, `IFuture` isn't really useful: the user is typically calling a specific submission function (like `submit_call`) and getting back a specific future type (like `CallFuture`), and they can use that future type in trait declarations and the like.
This PR removes the ambiguity and specialises `IFuture` for the second use-case - that of documenting what the executor expects from a future.
In more detail, we:
- Move `IFuture` to …
> Repurpose IFuture

- docs/source/guide/examples/background_processes.py
- docs/source/guide/examples/pi_iterations.py
- docs/source/guide/examples/prime_counting.py
- docs/source/guide/examples/slow_squares.py
- traits_futures/tests/i_pingee_tests.py
fixes #440 
This PR updates the static `_*_fired` methods with `observe` decorated methods.
Note to reviewer : I tested the examples locally but it would be a good idea to test them personally.
> Migrate static "_*_fired" methods with "observe" decorated methods

- setup.py
The `null` entry in `extras_require` isn't useful. I think there was a plan at one point to be able to do `pip install -e .[toolkit_name]` from CI scripts, but we're not doing that.
Closes #446.
> Remove the useless 'null' entry from extras_require

- docs/source/changes.rst
- docs/source/guide/examples/prime_counting.py
- docs/source/guide/intro.rst
- traits_futures/api.py
- traits_futures/background_progress.py
- traits_futures/base_future.py
- traits_futures/tests/background_progress_tests.py
- traits_futures/tests/test_api.py
This PR renames the `ProgressCancelled` exception to `TaskCancelled` and moves it to `base_future.py`. This is in anticipation of future task types that might want to re-use the same exception. (Notably the `StepsTask` in #367.)
Closes #445
> Rename ProgressCancelled to TaskCancelled

- docs/source/changes.rst
- docs/source/guide/examples/prime_counting.py
Some experimental changes that may fix the cancellation issue with the prime-counting demo script (#442):
- Use `Qt.QueuedConnection` as the connection type for the buttons. This is a workaround for a macOS-only issue where refreshes don't happen as often as expected.
- Never set the `future` held by the dialog to `None`; there's no good reason to do this, and it makes reasoning about correctness more difficult.
- Allow for the possibility that by the time we're executing the `cancel` method, the future is no longer cancellable.
@rahulporuri Do you have bandwidth to test this?
Closes #442 (I hope).
> Fix out-of-order cancellation

- .github/workflows/build-docs.yml
- .github/workflows/test-docs.yml
- setup.py
Using the latest version of Sphinx to build documentation is proving problematic: we're ending up with broken documentation builds too often as a result of Sphinx changes.
This PR doesn't actually pin the version of Sphinx to use, but does avoid Sphinx >= 4 for the moment. We can upgrade later when things seem more stable.
This PR also changes the workflows to use `pip install .[doc]`, so that the information about the packages needed for docs is in a single place.
Closes #456.
> Don't use Sphinx 4 for the moment

- docs/source/guide/examples/interruptible_task.py
- docs/source/guide/examples/non_interruptible_task.py
This PR fixes two examples that were raising within a Traits observer, albeit in a theoretically impossible situation. The PR replaces the `raise` with an `assert`. Context: deliberately raising an exception within a Traits listener is an antipattern, and we shouldn't feature that antipattern in our examples.
> Examples: don't raise in a Traits observer

- docs/source/changes.rst
- traits_futures/base_future.py
- traits_futures/tests/common_future_tests.py
This PR provides a quick fix for the regression reported in #466.
Note that a future created without a `_cancel` argument isn't really fully functional, but it's still useful in testing if those tests don't need to test cancellation.
> Allow BaseFuture instances to be instantiated without arguments

- docs/source/changes.rst
- traits_futures/base_future.py
- traits_futures/tests/common_future_tests.py
(cherry picked from commit 63005f7b9b9cc0711a386840d371e4a1f8e73a63)
This is a backport of the fix in #467 to the 0.3.x maintenance branch.
The code has already been reviewed. I'll self-merge when the CI completes.
> Allow BaseFuture instances to be instantiated without arguments (#467)

- .github/workflows/test-from-pypi.yml
- docs/source/changes.rst
We've successfully automated upload of sdists and wheels to PyPI, but we have nothing in place to test those uploads automatically.
This PR adds a workflow that can be triggered manually, and is also run every two weeks. It installs the latest Traits Futures wheel from PyPI, together with PySide2, and checks that all tests pass. It then does the same for the sdist.
The `pull_request:` trigger will be removed once it's established that this workflow is working correctly.
> Add workflow to validate PyPI installs

- traits_futures/tests/i_message_router_tests.py
- traits_futures/tests/test_ets_event_loop.py
This PR fixes a couple of minor gaps in the test coverage, including adding a test that explicitly exercises the context manager interface of the message senders.
> Fix a couple of minor test coverage gaps

- scripts/update_docs.py
Another debugging step in the automated documentation build: print the git config.
> Auto doc build debugging: print git config

- docs/source/guide/examples.rst
- docs/source/guide/toolkits.rst
In most of the `literalinclude` example scripts we skip the copyright headers, but in some we missed that. This PR fixes that.
> Skip copyright headers in literalincludes

- docs/source/changes.rst
- traits_futures/qt/event_loop_helper.py
This PR adds a compatibility fix for Qt6 support. Unfortunately there doesn't seem to be any reasonable way to avoid checking for both `exec` and `exec_` for the near future: PyQt6 _only_ has `exec`, while PySide2 _only_ has `exec_`. PySide6 and PyQt5 support both.
No tests because:
- ~support for Qt6 isn't yet in Pyface master~ support for Qt6 isn't yet in a Pyface release
- this code is effectively part of the test machinery anyway - it's not currently used by Traits Futures clients
Once Pyface has released support for Qt6, we should add GitHub Actions workflows for testing on the various flavours of Qt versions and wrappers. I'll open a separate issue for that.
> Try both 'exec' and 'exec_' methods on QCoreApplication.

- docs/source/changes.rst
- setup.py
- traits_futures/tests/test_ets_event_loop.py
This PR removes the `asyncio` and `null` entry points, and adjusts the tests accordingly. We're not removing the `AsyncioEventLoop` or its uses in testing: we're only removing the ability to do `export ETS_TOOLKIT=asyncio` and pick up an `AsyncioEventLoop` as a result. That functionality was questionable at best, is causing deprecation warnings in Python 3.10, and will become broken in future Python versions with the current code.
Rationale:
- The idea of asyncio as a drop-in replacement for Qt or Wx at this level doesn't make a lot of sense right now. There are ways it could be made to make sense in the future, but there would need to be a significant design phase, and we'd likely want to consider the whole of ETS rather than just Traits Futures.
- asyncio has a particular technical …
> Remove asyncio toolkit support

- .github/workflows/build-docs.yml
- .github/workflows/check-style.yml
- .github/workflows/publish-on-pypi.yml
- .github/workflows/run-tests.yml
- .github/workflows/test-docs.yml
- .github/workflows/test-from-pypi.yml
- .github/workflows/weekly-scheduled-tests.yml
This PR updates the Python versions in GitHub Actions workflows:
- Replace `3.10-dev` with `3.10`
- Make all Python versions strings (which is what they should have been all along, but the problem didn't become apparent until we a version of `3.10` was interpreted as `3.1`).
> Change 3.10-dev to 3.10, and make all Python versions strings

- docs/source/changes.rst
- docs/source/guide/examples/headless.py
- traits_futures/asyncio/event_loop.py
- traits_futures/asyncio/tests/test_asyncio_event_loop.py
- traits_futures/asyncio/tests/test_event_loop_helper.py
- traits_futures/asyncio/tests/test_pingee.py
- traits_futures/testing/test_assistant.py
This PR replaces the use of `asyncio.get_event_loop` in the Traits Futures core. ~There's a remaining example that still uses `get_event_loop`, but I'll address that separately.~
There are some remaining warnings in the test run resulting from the fact that we have no way to clean up asyncio event loops created through `ETSToolkit`, but I believe `ETSToolkit` should not have been supporting asyncio in the first place - see #490.
Together with #490, this addresses #491.
Also closes #333.
> Replace use of the deprecated asyncio.get_event_loop function.

- .gitignore
When using the most recent setuptools and pip, a `pip install` creates a `build` directory. This PR adds that `build` directory to the `.gitignore`.
> Add build directory to .gitignore

- .github/workflows/build-docs.yml
This PR adds a "workflow_dispatch" trigger to the build-docs workflow, so that we can trigger it directly (instead of, for example, having to find a trivial change to make to the source and rely on the resulting push to main to trigger the build).
> Permit doc builds through workflow_dispatch

- setup.py
The documentation build failed in PR #501, with error:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/hostedtoolcache/Python/3.8.[12](https://github.com/enthought/traits-futures/runs/6780129495?check_suite_focus=true#step:7:13)/x64/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sphinx/__main__.py", line [13](https://github.com/enthought/traits-futures/runs/6780129495?check_suite_focus=true#step:7:14), in <module>
from sphinx.cmd.build import main
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sphinx/cmd/build.py", line …
```
> Fix documentation build failure

- .github/workflows/weekly-scheduled-tests.yml
This PR updates the scheduled workflows to report failures to the main ETS channel rather than the more noisy bots channel, in the hope that they're more likely to be noticed there. Successes continue to be reported to the bots channel.
> Report cron job failures to main Slack channel, not bots channel

- docs/source/conf.py
- setup.py
This PR does the following - 
- Use the `sphinx_copybutton` extension when building the Sphinx documentation
- Make `sphinx-copybutton` a `docs` extra for the `traits-futures` package
Ref https://sphinx-copybutton.readthedocs.io/en/latest/
> Use the "sphinx-copybutton" extension in documentation

- .github/workflows/check-style.yml
- .github/workflows/run-tests.yml
- .github/workflows/weekly-scheduled-tests.yml
- pyproject.toml
The `pyproject.toml` file was missing information about the build system; this PR adds that information, and removes unnecessary installations of `wheel` and `setuptools` in the CI workflows.
> Add build-system section to pyproject.toml

- traits_futures/tests/common_future_tests.py
This PR fixes a test that uses `_task_returned` to return an exception rather than a result.
The test works, but it's potentially confusing: there's no good reason for it to be returning exception information instead of a result.
> Fix a test that returned an exception instead of a result

- .github/workflows/test-from-pypi.yml
- .github/workflows/weekly-scheduled-tests.yml
Now that 3.11 is released, we should be using it in place of 3.11-dev.
We also update test-from-pypi.yml to test _with_ PySide2 on Python 3.10, but to exclude PySide2 when testing with Python 3.11.
Test run for the install-from-pypi workflow, which was broken prior to this PR: https://github.com/enthought/traits-futures/actions/runs/3513252094
> Replace 3.11-dev with 3.11

- .github/workflows/run-tests.yml
- .github/workflows/test-from-pypi.yml
- .github/workflows/weekly-scheduled-tests.yml
This PR brings the CI back to working state on ubuntu-latest.
- Update the wx tests to use the ubuntu-22.04 wheel for wxPython; update the workflow to use ubuntu-latest
- Update apt-get requirements for Qt on Linux
- Use PySide6 throughout instead of PySide2
- Replace the 3rd party xvfb action with xvfb-run.
> Update CI for Ubuntu 22.04; remove 3rd party xvfb action

- .github/workflows/run-tests.yml
- .github/workflows/test-from-pypi.yml
- .github/workflows/weekly-scheduled-tests.yml
The current workflows fail with the recently-released PySide6 6.5.0, which requires the `libxcb-cursor` library to be present.
This PR adds `libxcb-cursor` to the list of apt-get dependencies in order to fix those workflows with PySide6 6.5.0.
> Add apt-get libxcb-cursor0 to workflows

- style-requirements.txt
This PR pins the `black` version to 22.x, to avoid the style workflow picking up and using the latest black version (which reports errors on the current codebase).
Some day we should update black and re-apply style fixes. But not today.
Related: https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy
> Pin black to version 22.x

- .github/workflows/run-tests.yml
- .github/workflows/test-from-pypi.yml
- .github/workflows/weekly-scheduled-tests.yml
- DEVELOP.rst
- docs/source/index.rst
- pyproject.toml
This PR removes support for Python 3.7, mainly because that's no longer supported by the dependent Traits library. The minimum Python version is now Python 3.8.
> Update the minimum Python version to 3.8
